---
title: "PARsTreatments_IceOff"
output: html_document
---

```{r}
library(tidyverse)
library(arrow)
library(readxl)
library(ggformula)
library(ggplot2)
library(mosaic)
library(mosaicCore)
library(readr)
library(dplyr)
library(lubridate)

pred_iceoutlong <- read_csv("exploration/pred_iceoutlong.csv")
PARs_joined <- read_csv("exploration/PARsInventory/PARs_joined.csv")
```

```{r}
pred_iceoutlong <- pred_iceoutlong %>% 
  mutate(DOW = str_remove(ID, "dow_"))%>% 
  mutate(DOW = as.numeric(DOW))
```

Join with PARs dataset
```{r}
PARs_IceOff <- PARs_joined %>%
```


```{r}
# 1. Create a temporary year column from start_date to match winter.year
  mutate(match_year = year(start_date)) %>%
  # 2. Join with pred_iceoutlong based on both conditions
  left_join(
    pred_iceoutlong %>% select(DOW, est),
    by = c("k_Lake_ID" = "DOW", "match_year" = "winter.year")) %>%
  # 3. Clean up the temporary year column
  select(-match_year) %>%
  rename(iceoff_est = est)
```

Creating subset of only CLP treatments that exceed 15% littoral area cutoff.
```{r}
Large_CLP_PARs <- PARs_IceOff %>% 
  filter(species_code == "CLP" & TreatmentSize_PercentofLittoral > 15)
```


```{r}
write.csv(Large_CLP_PARs, "Large_CLP_PARs_IceOff.csv", row.names = FALSE)
```

Notes: roughly 50 (out of 107) large CLP PARs treatments don't have joined ice out estimates. 35 of those are 2023-present. Of the rest, many are bays.