---
title: "Preparing_NativePlant_model"
output: html_document
---


```{r loading packages}
library(tidyverse)
library(arrow)
library(readxl)
library(dplyr)
library(readr)
library(lubridate)
library(sf)
library(here)
library(stringr)
library(ggplot2)
library(ggplotplus)
library(viridis)
library(gridExtra)
library(cowplot)

```



```{r load data}

  NativeResponse.e.old <- read_csv("~/IAPM Project/MAISRC-IAPM/analysis/CLP_Trt_NativePlantResponse/NativeResponse.e.csv")
  NativeResponse.p.old <- read_csv("~/IAPM Project/MAISRC-IAPM/analysis/CLP_Trt_NativePlantResponse/NativeResponse.p.csv")
  
CLP_trt_matrix <- read_csv("~/IAPM Project/MAISRC-IAPM/analysis/MVerhoeven_2020_model/2026 data/CLP_trt_lag_matrix_Sept9.csv")

Secchi <- read_csv("G:/Shared drives/Walsh Lab/Projects/MAISRC IAPM/Data/MPCA Water Quality/Secchi/MPCA_Secchi_2010_2025_Clean.csv")

Phosphorus <- read_csv("G:/Shared drives/Walsh Lab/Projects/MAISRC IAPM/Data/MPCA Water Quality/Phosphorus/MPCA_Phosphorus_2010_2025_Clean.csv")

#PI survey data. Row = one sample point
PI_surveys <- read_csv("G:/Shared drives/Walsh Lab/Projects/MAISRC IAPM/Data/PI Charter Data/PI_surveys_foo.csv")

#join LZ acres to PI_surveys
MN_lake_basin_littoral_zone <- read_csv(here("data", "MN_lake_basin_littoral_zone_15_ft_std.csv"))


```

```{r}
#delete duplicates
NativeResponse.e <- NativeResponse.e %>% 
  distinct(Lake.ID, Year, native_rich_mean, Acres_Chem, .keep_all = TRUE)

NativeResponse.p <- NativeResponse.p %>% 
  distinct(Lake.ID, Year, native_rich_mean, Acres_Chem, .keep_all = TRUE)

```

```{r water quality data}
###secchi
# 1.parse dates, extract year/month, filter, & average
secchi_averaged <- Secchi %>%
  mutate(
    # Convert dmy string to standard R Date format (YYYY-MM-DD)
    date = mdy(ActivityStartDate),
    year     = year(date),
    month    = month(date)
  ) %>%
  # Filter for April (4) through September (9) and valid Secchi values
  filter(month >= 4 & month <= 9, !is.na(ResultMeasureValue)) %>%
  # Group by lake (DOW) and year
  group_by(DOW, year) %>%
  # Calculate average Secchi depth per lake-year
  summarize(
    secchi   = mean(ResultMeasureValue, na.rm = TRUE),
    secchi.e = mean(ResultMeasureValue[month <= 6], na.rm = TRUE),
    .groups  = "drop"
  ) %>%
  # Replace potential NaN values (when a lake-year has no April-June samples) with NA
  mutate(secchi.e = ifelse(is.nan(secchi.e), NA, secchi.e))

# 2. Join the averaged Secchi values into your matrix
NativeResponse.e <- NativeResponse.e %>%
  left_join(secchi_averaged, by = c("Lake.ID" = "DOW", "Year" = "year"))




#LakeBrowser Secchi

Secchi_LakeBrowser_long <- LakeBrowser_2017_2025_clarity %>% 
  pivot_longer(
    cols = SD_201705:SD_202510, 
    names_to = "YearMonth", 
    values_to = "Secchi_Depth"
  )

Secchi_LakeBrowser_long <- Secchi_LakeBrowser_long %>%
  filter(nchar(YearMonth) <= 9)


Secchi_LakeBrowser_long <- Secchi_LakeBrowser_long %>%
  separate_wider_regex(
    YearMonth,
    patterns = c("SD_", Year = "\\d{4}", Month = "\\d{2}"),
    cols_remove = FALSE # Keeps the original YearMonth column
  ) %>%
  mutate(
    Year = as.numeric(Year),
    Month = as.numeric(Month)
  )

Secchi_LakeBrowser_long <- Secchi_LakeBrowser_long %>%
  select(-c(4:6))


#filter, & average
secchi_averaged <- Secchi_LakeBrowser_long %>%
  # Filter for April (4) through September (9) and valid Secchi values
  filter(Month >= 4 & Month <= 9, !is.na(Secchi_Depth)) %>%
  # Group by lake (DOW) and year
  group_by(Parent_DOW, Year) %>%
  # Calculate average Secchi depth per lake-year
  summarize(
    secchi   = mean(Secchi_Depth, na.rm = TRUE),
    secchi.e = mean(Secchi_Depth[Month <= 6], na.rm = TRUE),
    .groups  = "drop"
  ) %>%
  # Replace potential NaN values (when a lake-year has no April-June samples) with NA
  mutate(secchi.e = ifelse(is.nan(secchi.e), NA, secchi.e))

# 2. Join the averaged Secchi values into your matrix
NativeResponse.e <- NativeResponse.e %>%
  left_join(secchi_averaged, by = c("Lake.ID" = "Parent_DOW", "Year" = "Year"))
  rename(
    secchi.LakeBrowser   = secchi.x,
    secchi.e.LakeBrowser = secchi.e.x
  )

  
  secchi_averaged <- secchi_averaged %>%
    rename(
      LakeBrowserSecchi = secchi,
      LakeBrowserSecchi.e = secchi.e 
    )
  
  
  NativeResponse.p <- NativeResponse.p %>%
  left_join(secchi_averaged, by = c("Lake.ID" = "Parent_DOW", "Year" = "Year"))


  NativeResponse.p <- NativeResponse.p %>%
 mutate(
    # Replaces NA in PrevAugSecchi with the corresponding LakeBrowser.PrevAugSecchi value
    secchi = coalesce(secchi, LakeBrowserSecchi)
  ) %>%
    mutate(
    # Replaces NA in PrevAugSecchi with the corresponding LakeBrowser.PrevAugSecchi value
    secchi.e = coalesce(secchi.e, LakeBrowserSecchi.e)
  )


  NativeResponse.e <- NativeResponse.e %>%
 mutate(
    # Replaces NA in PrevAugSecchi with the corresponding LakeBrowser.PrevAugSecchi value
    secchi = coalesce(secchi, secchi.LakeBrowser)
  ) %>%
    mutate(
    # Replaces NA in PrevAugSecchi with the corresponding LakeBrowser.PrevAugSecchi value
    secchi.e = coalesce(secchi.e, secchi.e.LakeBrowser)
  )









###phosphorus
# 1.parse dates, extract year/month, filter, & average
phosphorus_averaged <- Phosphorus %>%
  mutate(
    year     = year(ActivityStartDate),
    month    = month(ActivityStartDate)
  ) %>%
  # Filter for April (4) through September (9) and valid phosphorus values
  filter(month >= 4 & month <= 9, !is.na(ResultMeasureValue)) %>%
  # Group by lake (DOW) and year
  group_by(DOW, year) %>%
  # Calculate average phosphorus per lake-year
  summarize(
    phosphorus   = mean(ResultMeasureValue, na.rm = TRUE),
    phosphorus.e = mean(ResultMeasureValue[month <= 6], na.rm = TRUE),
    .groups  = "drop"
  ) %>%
  # Replace potential NaN values (when a lake-year has no April-June samples) with NA
  mutate(phosphorus.e = ifelse(is.nan(phosphorus.e), NA, phosphorus.e))

# 2. Join the averaged Secchi values into your matrix
phosphorus_averaged <- phosphorus_averaged %>%
  mutate(DOW = as.numeric(DOW))

CLP_trt_matrix <- CLP_trt_matrix %>%
  left_join(phosphorus_averaged, by = c("Lake.ID" = "DOW", "Year" = "year"))

```

```{r native foo}
PI_surveys <- PI_surveys %>%
  mutate(DOW = as.numeric(DOW))




CLP_trt_matrix <- CLP_trt_matrix %>%
  left_join(
    PI_surveys %>% 
      select(DOW, year, SURVEY_START, native_rich, native_vegetated, survey_native_rich, nsamp),
    by = c("Lake.ID" = "DOW", "Year" = "year")
  ) %>%
  rename(native_rich_mean = native_rich)
    
  NativeResponse.e <- NativeResponse.e %>%
    mutate(NativeFOO_x_Richness = native_vegetated*survey_native_rich)
   
   NativeResponse.p <- NativeResponse.p %>%
    mutate(NativeFOO_x_Richness = native_vegetated*survey_native_rich)
     
```

```{r redo lag0}
CLP_trt_matrix <- CLP_trt_matrix %>%
  mutate(
    lag0 = case_when(
      lag0_before == 1 | lag0_after == 1 ~ 1,
      lag0_before == 0 & lag0_after == 0 ~ 0,
      TRUE ~ NA_real_ 
    )
  ) %>%
  select(-lag0_before, -lag0_after)


CLP_trt_matrix <- CLP_trt_matrix %>%
  mutate(
    # Take whichever value is not NA (checks acres_lag0_before first)
    trt_acres_lag0 = coalesce(acres_lag0_before, acres_lag0_after)
  ) %>%
  select(-acres_lag0_before, -acres_lag0_after)


CLP_trt_matrix <- CLP_trt_matrix %>%
  mutate(
    trt_date_lag0 = coalesce(date_lag0_before, date_lag0_after)
  ) %>%
  select(-date_lag0_before, -date_lag0_after)

#reorder columns
CLP_trt_matrix <- CLP_trt_matrix %>%
  relocate(lag1:lag8, .after = last_col())

```

```{r write raw dataset}
write.csv(CLP_trt_matrix, file = "~/IAPM Project/MAISRC-IAPM/analysis/CLP_Trt_NativePlantResponse/NativePlants_CLP_Trt.csv")

```


```{r create centered scaled vars}
# create centered scaled vars --------------------------------------------
#' Create centered variables (used in glms):
  CLP_trt_matrix$Snow.sc <- c(scale(CLP_trt_matrix$Snow))
  CLP_trt_matrix$secchi.sc <- c(scale(CLP_trt_matrix$secchi))
  CLP_trt_matrix$secchi.e.sc <- c(scale(CLP_trt_matrix$secchi.e))
  CLP_trt_matrix$phosphorus.sc <- c(scale(CLP_trt_matrix$phosphorus))
  CLP_trt_matrix$phosphorus.e.sc <- c(scale(CLP_trt_matrix$phosphorus.e))
  
 NativeResponse.e$Snow.sc <- c(scale(NativeResponse.e$Snow))
  NativeResponse.e$secchi.sc <- c(scale(NativeResponse.e$secchi))
  NativeResponse.e$secchi.e.sc <- c(scale(NativeResponse.e$secchi.e))
  NativeResponse.e$phosphorus.sc <- c(scale(NativeResponse.e$phosphorus))
  NativeResponse.e$phosphorus.e.sc <- c(scale(NativeResponse.e$phosphorus.e))
  
   NativeResponse.p$Snow.sc <- c(scale(NativeResponse.p$Snow))
  NativeResponse.p$secchi.sc <- c(scale(NativeResponse.p$secchi))
  NativeResponse.p$secchi.e.sc <- c(scale(NativeResponse.p$secchi.e))
  NativeResponse.p$phosphorus.sc <- c(scale(NativeResponse.p$phosphorus))
  NativeResponse.p$phosphorus.e.sc <- c(scale(NativeResponse.p$phosphorus.e))
  
  
    #combine lake and year to give a lk-yr field
  CLP_trt_matrix$lake_year <- paste(CLP_trt_matrix$Lake.x, CLP_trt_matrix$Year, sep = "")
 
```

```{r split early and peak}
    
# Split into early season (June or earlier: months 1-6)
NativeResponse.e <- CLP_trt_matrix %>%
  filter(month(SURVEY_START) <= 6)

# Split into late season (July or later: months 7-12)
NativeResponse.p <- CLP_trt_matrix %>%
  filter(month(SURVEY_START) >= 7)

#standardize date format
NativeResponse.e <- NativeResponse.e %>%
  mutate(trt_date_lag0 = mdy(trt_date_lag0))
NativeResponse.p <- NativeResponse.p %>%
  mutate(trt_date_lag0 = mdy(trt_date_lag0))

NativeResponse.e <- NativeResponse.e %>%
  mutate(SURVEY_START = mdy(SURVEY_START))
NativeResponse.p <- NativeResponse.p %>%
  mutate(SURVEY_START = mdy(SURVEY_START))


NativeResponse.e <- NativeResponse.e %>% 
  select(-Lake.ID.x, -trt_date_lag0.x, -trt_date_lag0.y) %>%
    left_join(
        NativeResponse.e.old %>% select(trt_acres_lag0, Lake.ID, SURVEY_START, Year, trt_date_lag0),
        by = c("trt_acres_lag0", "SURVEY_START", "Year")
    )

NativeResponse.p <- NativeResponse.p %>% 
  left_join(
        NativeResponse.p.old %>% select(trt_acres_lag0, Lake.ID, SURVEY_START, Year, trt_date_lag0),
        by = c("trt_acres_lag0", "SURVEY_START", "Year")
    )
```

```{r consecutive years trt}
 #fix Trt for early surveys
NativeResponse.e <- NativeResponse.e %>%
  mutate(
    # Assign 1 if treatment date occurred before survey date, otherwise 0
    Trt = if_else(trt_date_lag0 < SURVEY_START, 1, 0, missing = 0)
  )
NativeResponse.e <- NativeResponse.e %>%
  mutate(
    # Assign 1 if treatment date occurred before survey date, otherwise 0
    lag0 = if_else(trt_date_lag0 < SURVEY_START, 1, 0, missing = 0)
  )

NativeResponse.e <- NativeResponse.e %>%
  relocate(lag0, .before = lag1)

NativeResponse.p <- NativeResponse.p %>%
  relocate(lag0, .before = lag1)
   




    
  # Calculate consecutive years trt
  NativeResponse.e <- NativeResponse.e %>%
    mutate(
    cytrt = apply(across(lag0:lag8), 1, function(row) {
      # Count consecutive 1s starting from the first element (lag0)
      r <- rle(row == 1)
      if (r$values[1]) r$lengths[1] else 0
    })
  )
  
    NativeResponse.p <- NativeResponse.p %>%
    mutate(
    cytrt = apply(across(lag0:lag8), 1, function(row) {
      # Count consecutive 1s starting from the first element (lag0)
      r <- rle(row == 1)
      if (r$values[1]) r$lengths[1] else 0
    })
  )
    
    
    
  # calculate years untreated
  NativeResponse.e <- NativeResponse.e %>%
  mutate(
    yutrt = apply(across(lag0:lag8), 1, function(row) {
      # Count consecutive 0s starting from the first element (lag0)
      r <- rle(row == 0)
      if (r$values[1]) r$lengths[1] else 0
    })
  )
  
  NativeResponse.p <- NativeResponse.p %>%
  mutate(
    yutrt = apply(across(lag0:lag8), 1, function(row) {
      # Count consecutive 0s starting from the first element (lag0)
      r <- rle(row == 0)
      if (r$values[1]) r$lengths[1] else 0
    })
  )
    
    #zeros for where we know there was no treatment
  NativeResponse.e <- NativeResponse.e %>% 
     mutate(perc.lit.chem = if_else(Trt == 0,0, perc.lit.chem))
  
  NativeResponse.p <- NativeResponse.p %>% 
     mutate(perc.lit.chem = if_else(Trt == 0,0, perc.lit.chem))
  
    NativeResponse.e <- NativeResponse.e %>% 
     mutate(Acres_Chem = if_else(Trt == 0,0, Acres_Chem))
    
  
```

```{r write final datasets}
write.csv(NativeResponse.e, file = "~/IAPM Project/MAISRC-IAPM/analysis/CLP_Trt_NativePlantResponse/NativeResponse.e.csv")
write.csv(NativeResponse.p, file = "~/IAPM Project/MAISRC-IAPM/analysis/CLP_Trt_NativePlantResponse/NativeResponse.p.csv")
```




```{r bug fixing}
NativeResponse.p <- NativeResponse.p %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27002800, 52.63, Lake.area.acre))

pcri.p <- pcri.p %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27002800, 52.63, Lake.area.acre))


NativeResponse.e <- NativeResponse.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27002800, 52.63, litt.ac))
pcri.e <- pcri.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27002800, 52.63, litt.ac))



NativeResponse.e <- NativeResponse.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27003400, 79.12, Lake.area.acre))
pcri.e <- pcri.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27003400, 79.12, Lake.area.acre))


NativeResponse.p <- NativeResponse.p %>%
  mutate(litt.ac = if_else(Lake.ID == 27003400, 53, litt.ac))
pcri.p <- pcri.p %>%
  mutate(litt.ac = if_else(Lake.ID == 27003400, 53, litt.ac))

NativeResponse.e <- NativeResponse.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27004500, 22.03, Lake.area.acre))
pcri.e <- pcri.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27004500, 22.03, Lake.area.acre))

NativeResponse.e <- NativeResponse.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27010300, 22.98 , litt.ac))
pcri.e <- pcri.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27010300, 22.98 , litt.ac))


NativeResponse.e <- NativeResponse.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27004400, 16 , litt.ac))
pcri.e <- pcri.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27004400, 16 , litt.ac))

NativeResponse.e <- NativeResponse.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27005700, 11 , Lake.area.acre))
pcri.e <- pcri.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27005700, 11 , Lake.area.acre))

NativeResponse.e <- NativeResponse.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27066900, 6 , Lake.area.acre))
pcri.e <- pcri.e %>%
  mutate(Lake.area.acre = if_else(Lake.ID == 27066900, 6 , Lake.area.acre))
NativeResponse.e <- NativeResponse.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27066900, 6 , litt.ac))
pcri.e <- pcri.e %>%
  mutate(litt.ac = if_else(Lake.ID == 27066900, 6 , litt.ac))

pcri.e <- pcri.e %>% 
     relocate(LK_AREA, .before = litt.ac)
pcri.p <- pcri.p %>% 
     relocate(LK_AREA, .before = litt.ac)

pcri.e <- pcri.e %>% 
     relocate(Lake.area.acre, .before = litt.ac)
pcri.p <- pcri.p %>% 
     relocate(Lake.area.acre, .before = litt.ac)
```

```{r APM IAPM permitted acres}
permits <- read.csv("G:/Shared drives/Walsh Lab/Projects/MAISRC IAPM/Data/Treatment Data/apm_iapm_permit_detail.csv",
                               na.strings=c("NA", "NULL"))
lake_basin_morphology_df <- read_csv("~/IAPM Project/MAISRC-IAPM/data/MN_lake_basin_littoral_zone_15_ft_std.csv")

#setting up IAPM permit data
permits <- apm_iapm_permit_detail %>%
  dplyr::select(permit_number, permit_type, 
                water_resource_names, water_resource_numbers,
                treatment_method, species,
                permit_approved_acres_1997:permit_approved_acres_2025)

permits[, 7:35][is.na(permits[, 7:35])] <- 0

permits_long <- permits

colnames(permits_long)[7:35] <- 1997:2025


permits_long <- permits_long %>%
  filter(permit_type == "Aquatic Plant Management") %>%
  pivot_longer(cols=`1997`:`2025`, 
               names_to="year",
               values_to="approved_acres") %>%
  mutate(year=as.numeric(year))

#rename columns
permits_long <- permits_long %>% 
  rename(DOW = water_resource_numbers) %>%
  filter(approved_acres > 0) %>%
  filter(approved_acres != "NULL" & !is.na(approved_acres))

  
permits_summarized <- permits_long %>% 
  mutate(approved_acres = as.numeric(approved_acres)) %>%
  group_by(DOW, year) %>% 
  summarize(
    total_approved_acres = sum(approved_acres, na.rm = TRUE),
    .groups = "drop"
  )  

permits_summarized <- permits_summarized %>% 
  mutate(total_approved_acres = round(total_approved_acres, 2))

NativeResponse.e <- NativeResponse.e %>% 
  mutate(Lake.ID = as.character(Lake.ID)) %>%
  left_join(permits_summarized, by = c("Lake.ID" = "DOW", "Year" = "year"))

NativeResponse.e <- NativeResponse.e %>% 
  mutate(
    Lake.ID = as.character(Lake.ID),
    Year_prev = Year - 1  # Create key for previous year
  ) %>% 
  left_join(
    permits_summarized %>% mutate(DOW = as.character(DOW)), 
    by = c("Lake.ID" = "DOW", "Year_prev" = "year")
  ) %>% 
  select(-Year_prev) %>%
  rename(lag1_permitted_acres = total_approved_acres)

NativeResponse.p <- NativeResponse.p %>% 
  mutate(Lake.ID = as.character(Lake.ID)) %>%
  left_join(permits_summarized, by = c("Lake.ID" = "DOW", "Year" = "year"))



#perc LZ
NativeResponse.e <- NativeResponse.e %>% 
  mutate(lag1_APM_perc_lit = (lag1_APM_acres/litt.ac)*100)


NativeResponse.p <- NativeResponse.p %>% 
  mutate(APM_perc_lit = (APM_permitted_acres/litt.ac)*100) %>%
  mutate(APM_perc_lit = round(APM_perc_lit, 2))

NativeResponse.p$APM_perc_lit[is.na(NativeResponse.p$APM_perc_lit)] <- 0
NativeResponse.e$lag1_APM_perc_lit[is.na(NativeResponse.e$lag1_APM_perc_lit)] <- 0
```

