---
title: "PARsSummaryStats"
output: html_document
---

# MAISRC IAPM Phase I
#This code creates summaries for DNR control grant PARs Final Query, cleaned using PARsClean code in Melina's workspace

# Packages and load in data

```{r, results='hide', message = FALSE}
library(tidyverse)
library(arrow)
library(readxl)
library(ggformula)
library(ggplot2)
library(mosaic)
library(mosaicCore)
library(readr)

MN_Lakes_Areas <- read_csv("~/IAPM Project/MAISRC-IAPM/exploration/PARsInventory/1. PARs + Littoral Area/MN_Lakes_Areas.csv")
all_IAPM_treatments <- read_csv("~/IAPM Project/MAISRC-IAPM/outputdata/all_IAPM_treatments.csv")
PARs <- read_excel("~/IAPM Project/PARs-query-FINAL_exported5-27-2026.xlsx")
```

Add target species to all_IAPM_treatments.csv
```{r}
PARs_grouped <- all_IAPM_treatments %>%
  left_join(
    PARs %>% select(Permit_number, App_year, species_code),
    by = c("permit_number" = "Permit_number", "treatment_year" = "App_year") 
  )
PARs_grouped <- PARs_grouped %>%
  filter(!is.na(species_code))
```


Join with reference lake area data
```{r}
MN_Lakes_Areas$DOW <- as.double(MN_Lakes_Areas$DOW)
PARs_grouped$DOW <- as.double(PARs_grouped$DOW)
PARs_joined <- PARs_grouped %>%
  left_join(
    MN_Lakes_Areas,
    by = c("DOW" = "DOW")
  )
#Calculating treatment area as % of lake area and littoral area
PARs_joined$TreatmentSize_PercentofLake <- (PARs_joined$treatment_size / PARs_joined$LakeAreaAcres) * 100
PARs_joined$TreatmentSize_PercentofLittoral <- (PARs_joined$treatment_size / PARs_joined$ObservedLittoralZone_Acres) * 100
```


PARs count by target species:
```{r}
tally(~species_code, data = PARs_joined)
```

```{r}
gf_bar(~treatment_year, fill = ~species_code, data = PARs_joined)
```

Histograms. Filtering out treatments above 120% area for now until we figure out what is up.
```{r}
PARs_joined%>%filter(species_code=="EWM")%>%filter(TreatmentSize_PercentofLake <= 120)%>%gf_histogram(~TreatmentSize_PercentofLake, data = PARs_joined, main = "EWM",  xlab = "EWM TreatmentSize_PercentofLake")

PARs_joined%>%filter(species_code=="EWM")%>%filter(TreatmentSize_PercentofLake <= 120)%>%gf_histogram(~TreatmentSize_PercentofLittoral, data = PARs_joined, main = "EWM",  xlab = "EWM TreatmentSize_PercentofLittoral")

PARs_joined%>%filter(species_code=="CLP")%>%filter(TreatmentSize_PercentofLake <= 120)%>%gf_histogram(~TreatmentSize_PercentofLake, data = PARs_joined, main = "CLP",  xlab = "CLP TreatmentSize_PercentofLake")

PARs_joined%>%filter(species_code=="CLP")%>%filter(TreatmentSize_PercentofLake <= 120)%>%gf_histogram(~TreatmentSize_PercentofLittoral, data = PARs_joined, main = "CLP",  xlab = "CLP TreatmentSize_PercentofLittoral")
```


```{r}
#Number of treatments larger than 15% of littoral area for EWM and CLP.
sum(~ (TreatmentSize_PercentofLittoral > 15 & species_code == "EWM"),
    data = PARs_joined, na.rm = TRUE)

sum(~ (TreatmentSize_PercentofLittoral > 15 & species_code == "CLP"),
    data = PARs_joined, na.rm = TRUE)

```
```{r}
write.csv(PARs_joined, "PARs_joined.csv", row.names = FALSE)
```

